/**
 * This file is generated only once. If it already exists, it will not be overwritten.
 * You can safely add custom exports, re-exports, or any other code here as needed.
 * Your customizations will be preserved across SDK regenerations.
 */

// Re-export everything from client
export * from './client';

// Re-export all error types from @blimu/fetch for instanceof checks
export * from '@blimu/fetch';

// Re-exports for better ergonomics
export * from './utils';
export * as Schema from './schema';
export * as ZodSchema from './schema.zod';
export { BulkResourcesService } from './services/bulk_resources';
export { BulkRolesService } from './services/bulk_roles';
export { EntitlementsService } from './services/entitlements';
export { AuthJwksService } from './services/auth_jwks';
export type { JWK, JWKSet } from './token-verifier';
export { PlansService } from './services/plans';
export { ResourceMembersService } from './services/resource_members';
export { ResourcesService } from './services/resources';
export { RolesService } from './services/roles';
export { UsageService } from './services/usage';
export { UsersService } from './services/users';

// Re-export token verifier for backward compatibility. This is custom code that is not generated by the codegen.
export * from './token-verifier';
export type * from '@blimu/types';
